spring.application.name=Supermarket Billing System
server.port=8091

# MySQL Database Configuration
# spring.datasource.url=jdbc:mysql://sql12.freesqldatabase.com:3309/
# spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# spring.datasource.username=sql12774893
# spring.datasource.password=HHHUEhaM9J


spring.datasource.url=jdbc:mysql://localhost:3309/billingsystem
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Logging Configuration
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# CORS Configuration
# Use comma-separated values for multiple origins, or * for all origins
# Example: cors.allowed-origins=http://localhost:3000,https://example.com
cors.allowed-origins=*

# JWT Configuration
jwt.expiration=86400000

# Allow circular references as a fallback
spring.main.allow-circular-references=true
#Mail configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=afreenaa685@gmail.com
spring.mail.password=timy nnxl fkin mwdf
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


# App reset link
app.reset-password-url=http://localhost:8089/email-forgot-password